export const masterTags = [
  { tag: "Billing error", description: "Wrong amount charged, invoice issue, payment failure" },
  { tag: "Refund request", description: "Customer wants money back for a payment or subscription" },
  { tag: "Pricing confusion", description: "Customer doesn't understand pricing or plan structure" },
  { tag: "Subscription cancellation", description: "Wants to cancel or stop a recurring payment" },
  { tag: "Login issue", description: "Can't log in, reset password, 2FA problems" },
  { tag: "Account locked", description: "Access denied due to security or system lock" },
  { tag: "Account setup", description: "Needs help creating or configuring their account" },
  { tag: "Permission issue", description: "Can't access something due to role or team settings" },
  { tag: "Bug", description: "Technical issue, malfunction or broken feature" },
  { tag: "Slow performance", description: "App or feature is slow or laggy" },
  { tag: "Mobile app issue", description: "Problem specific to the mobile version" },
  { tag: "Integration issue", description: "External tool or service not connecting properly" },
  { tag: "API error", description: "Problem with API access, authentication or limits" },
  { tag: "Data problem", description: "Missing, incorrect or unsynced data" },
  { tag: "Feature request", description: "Suggestion for new feature or improvement" },
  { tag: "Feature limitation", description: "Customer blocked by something the product can't do" },
  { tag: "UI feedback", description: "Complaints or suggestions about design or layout" },
  { tag: "Order not received", description: "Package or item hasn't arrived" },
  { tag: "Wrong item", description: "Received something other than what was ordered" },
  { tag: "Return request", description: "Customer wants to return an item" },
  { tag: "Shipping delay", description: "Package is taking longer than expected" },
  { tag: "How-to question", description: "Customer wants to understand how something works" },
  { tag: "Configuration help", description: "Needs help setting something up correctly" },
  { tag: "Eligibility question", description: "Asks if they qualify for a feature, discount or service" },
  { tag: "Language issue", description: "Customer mentions incorrect or missing translations" },
  { tag: "Notification issue", description: "Not receiving alerts, emails or in-app messages" },
  { tag: "Analytics question", description: "Confused by stats, reports or dashboards" },
  { tag: "Custom field issue", description: "Something wrong with user-created fields or properties" },
  { tag: "Team management", description: "Wants to add/remove or manage users on their account" },
  { tag: "Security concern", description: "Concern about credentials, access or data protection" }
]; 